/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void appHasName() {
        App classUnderTest1 = new App();
        assertNotNull("app should have a name", classUnderTest1.getName());
    }
}
